/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:c33f6e3e-d28b-403e-8eb6-db100ea8c586",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_rBbJSOB8C",
    "aws_user_pools_web_client_id": "71rlog84mkfgtmkm1vgs24lv12",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://rwcbn4772nh75cg3vufnvbfssu.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-bpkrq3ixdzavrc6fr6j3jo6nj4",
    "aws_user_files_s3_bucket": "amplifyreactgraphql2a74aa5439d18452294afc2016df203140-staging",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
